-- Production-ready data model for B&M Exclusive
create extension if not exists pgcrypto;
create table public.profiles(id uuid primary key references auth.users on delete cascade, full_name text, role text not null default 'staff' check(role in('admin','staff')));
create table public.vehicles(id uuid primary key default gen_random_uuid(), slug text unique not null, brand text not null, model text not null, year int, category text, description text, status text default 'available' check(status in('available','reserved','maintenance','inactive')), published boolean default false, featured boolean default false, seats int, power text, transmission text, acceleration text, color text, location text, price_day numeric(10,2), price_weekend numeric(10,2), deposit numeric(10,2), cover_url text, gallery jsonb default '[]', seo_title text, seo_description text, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.offers(id uuid primary key default gen_random_uuid(), vehicle_id uuid references public.vehicles on delete cascade, label text not null, description text, price numeric(10,2), old_price numeric(10,2), starts_at timestamptz, ends_at timestamptz, active boolean default true, created_at timestamptz default now());
create table public.leads(id uuid primary key default gen_random_uuid(), name text not null, email text, phone text, vehicle_id uuid references public.vehicles on delete set null, date_from date, date_to date, source text default 'web', status text default 'new', estimated_value numeric(10,2), notes text, created_at timestamptz default now());
create table public.bookings(id uuid primary key default gen_random_uuid(), vehicle_id uuid references public.vehicles, lead_id uuid references public.leads, client_name text not null, date_from date not null, date_to date not null, status text default 'pending', total numeric(10,2), deposit_paid numeric(10,2) default 0, delivery_location text, notes text, created_at timestamptz default now());
alter table public.profiles enable row level security;alter table public.vehicles enable row level security;alter table public.offers enable row level security;alter table public.leads enable row level security;alter table public.bookings enable row level security;
create policy "public read published vehicles" on public.vehicles for select using(published=true);
create policy "public read active offers" on public.offers for select using(active=true and (ends_at is null or ends_at>now()));
create policy "staff manage vehicles" on public.vehicles for all using(exists(select 1 from public.profiles p where p.id=auth.uid())) with check(exists(select 1 from public.profiles p where p.id=auth.uid()));
create policy "staff manage offers" on public.offers for all using(exists(select 1 from public.profiles p where p.id=auth.uid())) with check(exists(select 1 from public.profiles p where p.id=auth.uid()));
create policy "staff manage leads" on public.leads for all using(exists(select 1 from public.profiles p where p.id=auth.uid())) with check(exists(select 1 from public.profiles p where p.id=auth.uid()));
create policy "staff manage bookings" on public.bookings for all using(exists(select 1 from public.profiles p where p.id=auth.uid())) with check(exists(select 1 from public.profiles p where p.id=auth.uid()));
